title: My Blog
author: 
description: A journal 
markdown: kramdown

kramdown:
  input: GFM
  footnote_nr: 1
  hard_wrap: false
  syntax_highlighter: rouge

plugins:
  - jekyll-sitemap

url: "https://merdeki.github.io"
baseurl: "/blog" 
